server:
  port: 8080

# Microservice / application name
spring:
  application:
    name: Application
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:~/h2/app_db;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  jpa:
   hibernate:
    ddlAuto: update

